 CREATE TRIGGER trg_UpdateDiscount
   ON Contracty
   AFTER INSERT, UPDATE, DELETE
   AS
   BEGIN
   SET NOCOUNT ON;

   UPDATE STUDENT
   SET DISCNT=
   CASE
   WHEN TOTALCOST BETWEEN 50000 and 70000 THEN 5
   WHEN TOTALCOST BETWEEN 70001 AND 80000 THEN 6
   WHEN TOTALCOST BETWEEN 80001 AND 100000 THEN 10
   ELSE 0
   END
   FROM STUDENT
   INNER JOIN (
   SELECT CONTRACTY.ID_STUD, SUM (COURSE.COST) AS TOTALCOST
   FROM CONTRACTY
   JOIN COURSE ON COURSE.ID_CRS =CONTRACTY.ID_CRS
   WHERE CONTRACTY.ID_STUD IN (SELECT ID_STUD FROM inserted UNION SELECT ID_STUD FROM deleted)
   GROUP BY CONTRACTY.ID_STUD) AS COSTSUMMARY ON STUDENT.ID_STUD =COSTSUMMARY.ID_STUD;
   END;