
update STUDENT set SX='Ж' where ID_STUD=5;
update TEACHER set SAL=250 where SURNAMETCH='Исаева';
SELECT *
FROM STUDENT
SELECT *
FROM TEACHER

delete from STUDENT where ID_STUD=4;
delete from TEACHER where ID_Tch=4;
SELECT *
FROM STUDENT
SELECT *
FROM TEACHER
SELECT *
FROM COURSE
SELECT *
FROM CONTRACTY