SELECT *
FROM COURSE
WHERE TITLE LIKE '%SQL%'
ORDER BY COST

SELECT TITLE, COST
FROM COURSE
WHERE TYPCRS LIKE '%Начальный%'

SELECT TITLE
FROM COURSE
WHERE (COST < 1500 AND TYPCRS like '%Начальный%')

SELECT SURNAME_STUD, NAME_STUD, OTCH_STUD , CONT, DISCNT
FROM STUDENT
WHERE ORG like '%КГТА%'

SELECT SURNAME_STUD, NAME_STUD, OTCH_STUD , CONT, ORG
FROM STUDENT
WHERE  SURNAME_STUD like 'К%'
ORDER BY ORG

SELECT SURNAME_STUD, NAME_STUD, OTCH_STUD , CONT, ORG
FROM STUDENT
WHERE  NAME_STUD like 'А%' AND SX LIKE '%Ж%'
ORDER BY ORG

SELECT SURNAME_STUD,NAME_STUD, OTCH_STUD
FROM STUDENT
WHERE ORG like '%КГТА%' AND SX like '%Ж%' and (NOT( NAME_STUD like '%я' or NAME_STUD like '%ь'))

SELECT SURNAMETCH, NAMETCH, OTCHTCH, CONTTCH, DOL
FROM TEACHER
WHERE SAL >= 600 and SAL <=900
ORDER BY SURNAMETCH, NAMETCH, OTCHTCH