CREATE TABLE FILM(
ID_KOPII INT PRIMARY KEY NOT NULL,
NAME_FILM VARCHAR (30),
KAT_FILM VARCHAR (30),
DLIT INT,
PRICE  MONEY, 
DATE_VIP DATE,
DATE_VID DATE,
DATE_VOZ DATE,
);

CREATE TABLE CLIENT
(ID_CL INT PRIMARY KEY NOT NULL,
SURNAME_CL VARCHAR(20),
NAME_CL VARCHAR (20),
OTCH VARCHAR(20),
YEAR_CL DATE,
ADDRESS_CL VARCHAR(50),
ID_KOPII INT FOREIGN KEY REFERENCES FILM (ID_KOPII) ON DELETE CASCADE,
NUMBER_CARD INT,
);
CREATE TABLE SOTRUDNIK
( ID_NUM INT PRIMARY KEY NOT NULL,
SURNAME_ST VARCHAR(20),
NAME_ST VARCHAR (20),
OTCH VARCHAR(20),
DOLZH VARCHAR(30), 
INN INT,
ID_CL INT FOREIGN KEY REFERENCES CLIENT (ID_CL) ON DELETE CASCADE
);